const tasks = [
    {
        _id: '1',
        name: 'Shopping list Shopping list Shopping list ',
        created: 'December 20, 2022',
        category: 'Random Thought',
        content: 'Tomatoes, bread Tomatoes, bread',
        dates: 'я пошел 03/05/2022, и пришел 05/11/2022',
        completed: false,
    },
    {
        _id: '2',
        name: 'The theory',
        created: 'April 25, 2022',
        category: 'Random Thought',
        content: 'The evolutions',
        dates: '',
        completed: false,
    },
    {
        _id: '3',
        name: 'New Feature',
        created: 'May 05, 2022',
        category: 'Task',
        content: 'Tomatoes, bread',
        dates: '03/5/2022, 05/5/2022',
        completed: false,
    },
    {
        _id: '4',
        name: 'William Gaddis',
        created: 'April 20, 2022',
        category: 'Idea',
        content: 'Power',
        dates: '',
        completed: true,
    },
    {
        _id: '5',
        name: 'New Feel',
        created: 'May 15, 2022',
        category: 'Task',
        content: 'Tomatoes, bread',
        dates: '3/5/2022, 5/5/2022',
        completed: false,
    },
    {
        _id: '6',
        name: 'Active',
        created: 'April 20, 2022',
        category: 'Idea',
        content: 'Power',
        dates: '',
        completed: true,
    },
    {
        _id: '7',
        name: 'all',
        created: 'May 20, 2022',
        category: 'Idea',
        content: 'Tomatoes, bread',
        dates: '3/5/2022, 5/5/2022',
        completed: false,
    },
];

export default tasks;